ses_statCorr <- function(line_color = 'black',
                       line_type = 'dashed',
                       corr_method = 'pearson',
                       ln_method = 'lm',
                       se = F,
                       line_size = 1,
                       separate_by = ',',
                       label_x = NULL,
                       label_y = NULL,
                       text_size = 4) {
  list(ggplot2::geom_smooth(color = line_color,
               linetype = line_type,
               size = line_size, method = ln_method,
               alpha = 0.2, se = se, weight = 0.8),
       stat_cor(p.accuracy = 0.01, method = corr_method,
                        label.sep = separate_by,
                        label.x = label_x,
                        label.y = label_y,
                size = text_size))
}
